### ISSUE TITLE
The sensitivity of some commands is... somewhat strange.

### ISSUE THREAD

**Issue by AJAL8000** [03-JS/LC-VEGA#1]
The command to turn the lights on or off, or tell Vega to stop talking, does not work at a certain sensitivity (say 6.9), however commands like Teleport or Transmit or Disable something do it correctly.

Going down to 6.5 or 6 "fixes" the problem (and it still has a hard time capturing the command) but it causes too many false positives, causing the Transmit command to go crazy and send all kinds of messages, or Vega to say "No problem" in the middle of nowhere.

I guess the problem is that Vega has a hard time capturing certain commands while others are very easy to capture. Making it so that in 6.9 some commands work fine and others stop working, while in 6, some commands are activated by mistake while others just start working.

**Comment by 03-JS** [comment]
This is a known problem with Windows Speech Recognition. Nothing I can do to fix it.

The next update will have some features that will help alleviate this problem, but it'll still happen nonetheless
