### ISSUE TITLE
The mod doesn't work as it should

### ISSUE THREAD

**Issue by gLozeen** [03-JS/LC-VEGA#12]
Once installed, VEGA should introduce itself as shown in the video in the README.
But instead he remains completely silent, and even if I try to talk to him, he won't answer.
What am I doing wrong? Maybe I downloaded the wrong language for speech recognition or something like that.

**Comment by gLozeen** [comment]
It seems that having "Advanced Speech Recognition" installed does not guarantee that speech recognition is installed. In the end, I installed it and VEGA answers me, but he never gave me a greeting, although I reinstalled the mod several times (

**Comment by 03-JS** [comment]
The greeting only happens in the first installation, but since you didn't have speech recognition, it wasn't able to play it
