### ISSUE TITLE
Vega dont react

### ISSUE THREAD

**Issue by Quntix** [03-JS/LC-VEGA#5]
I installed vega with my friends, we joined and vega hear my friends and react, but ignoring me, i reinstalled windows 2 times, tried different microphones, but nothing works

**Comment by 03-JS** [comment]
Did you set up Windows speech recognition?

**Comment by Quntix** [comment]
![image](https://github.com/03-JS/LC-VEGA/assets/166743771/132fc63d-38e8-4f71-b360-59cbd1215894)
i cant for some reasons here, sorry for different language

**Comment by Quntix** [comment]
ohh wait
i think i found the solution, i need to download Windows speech recognition

**Comment by Quntix** [comment]
Im so dumb, im so sorry, i downloaded Windows speech recognition, its working
thank you so much
