### ISSUE TITLE
Extra Commands?

### ISSUE THREAD

**Issue by Fellow9000** [03-JS/LC-VEGA#7]
Vega's utility in solo runs is incredible, but would it be possible to add custom commands through the config menu, similar to how voice commands could be modified?

There are many custom command mods that give the terminal more functionality, but there's no way to add these to Vega's current list of voice commands. I've used NavarroTech's TerminalKeyBindings and Beauver's ExtraTerminalCommands alongside Vega, using TerminalKeyBindings to send written commands remotely into the terminal. Would adding a similar function work, like adding a predetermined typed command into the terminal after Vega receives the respective custom voice command?

**Comment by 03-JS** [comment]
I won't add the ability to add custom commands with custom functionality through the config ever, I don't even know where I would start with that (or if it's even doable)

What I **can** do however is add compatibility with those mods, which I'll be more than happy to do once I get back to working on this mod

**Comment by Fellow9000** [comment]
Ok, much appreciated. Thanks for the response!

**Comment by 03-JS** [comment]
I just checked the ExtraTerminalCommands mod and didn't see anything I could add compatibility with as VEGA already does all of those things and more in some cases
