### ISSUE TITLE
Vega can banish Cruisers from orbit

### ISSUE THREAD

**Issue by Fellow9000** [03-JS/LC-VEGA#8]
I just tested something that I though wouldn't be an issue. If you own a cruiser and are orbiting a planet, you can still tell Vega to disengage the magnet, sending the vehicle into the abyss. Reloading the save will not bring the cruiser back.

Hopefully this could be fixed similar to how he will refuse to open the ship doors in orbit.

**Comment by 03-JS** [comment]
Use [Magnet Lock](https://thunderstore.io/c/lethal-company/p/DarthLilo/MagnetLock/). Prevents this issue from happening
